export const taskData = {
  tasks: [
    {
      id: 1,
      assignedTo: "John Doe",
      doc_id: "doc1",
      status: "Completed",
      priority: "High",
      assignedDate: "2024-01-01",
      dueDate: "2024-01-10",
      completionDate: "2024-01-09",
      reopened: false,
      completionTime: 90, // e.g., represents 90%
    },
    {
      id: 2,
      assignedTo: "Jane Smith",
      doc_id: "doc2",
      status: "Pending",
      priority: "Medium",
      assignedDate: "2024-02-01",
      dueDate: "2024-02-10",
      completionDate: "",  // Empty for pending tasks
      reopened: false,
      completionTime: null,
    },
    {
      id: 3,
      assignedTo: "Alice Johnson",
      doc_id: "doc3",
      status: "Overdue",
      priority: "High",
      assignedDate: "2024-03-01",
      dueDate: "2024-03-10",
      completionDate: "",
      reopened: false,
      completionTime: null,
    },
    {
      id: 4,
      assignedTo: "Bob Brown",
      doc_id: "doc4",
      status: "Completed",
      priority: "Low",
      assignedDate: "2024-04-01",
      dueDate: "2024-04-10",
      completionDate: "2024-04-08",
      reopened: true,
      completionTime: 80,
    },
    {
      id: 5,
      assignedTo: "Charlie Davis",
      doc_id: "doc5",
      status: "Completed",
      priority: "Medium",
      assignedDate: "2024-05-01",
      dueDate: "2024-05-10",
      completionDate: "2024-05-09",
      reopened: false,
      completionTime: 95,
    },
    {
      id: 6,
      assignedTo: "Emily Harris",
      doc_id: "doc6",
      status: "Pending",
      priority: "High",
      assignedDate: "2024-06-01",
      dueDate: "2024-06-10",
      completionDate: "",
      reopened: false,
      completionTime: null,
    },
    {
      id: 7,
      assignedTo: "Frank Moore",
      doc_id: "doc7",
      status: "Overdue",
      priority: "Low",
      assignedDate: "2024-07-01",
      dueDate: "2024-07-10",
      completionDate: "",
      reopened: false,
      completionTime: null,
    },
    {
      id: 8,
      assignedTo: "Grace Lee",
      doc_id: "doc8",
      status: "Completed",
      priority: "Medium",
      assignedDate: "2024-08-01",
      dueDate: "2024-08-10",
      completionDate: "2024-08-10",
      reopened: false,
      completionTime: 100,
    },
    {
      id: 9,
      assignedTo: "Henry Kim",
      doc_id: "doc9",
      status: "Completed",
      priority: "High",
      assignedDate: "2024-09-01",
      dueDate: "2024-09-10",
      completionDate: "2024-09-09",
      reopened: false,
      completionTime: 85,
    },
    {
      id: 10,
      assignedTo: "Isabella Garcia",
      doc_id: "doc10",
      status: "Pending",
      priority: "Low",
      assignedDate: "2024-10-01",
      dueDate: "2024-10-10",
      completionDate: "",
      reopened: false,
      completionTime: null,
    },
  ],
};
