export const taskData = {
    tasks: [
      {
        id: 1,
        assignedTo: "John Smith",
        status: "Completed",
        priority: "High",
        assignedDate: "2024-01-01",
        dueDate: "2024-01-15",
        completionDate: "2024-01-14",
        reopened: false,
        completionTime: 90,
      },
      {
        id: 2,
        assignedTo: "Jane Doe",
        status: "Completed",
        priority: "Medium",
        assignedDate: "2024-01-05",
        dueDate: "2024-01-20",
        completionDate: "2024-01-21",
        reopened: true,
        completionTime: 110,
      },
      {
        id: 3,
        assignedTo: "John Smith",
        status: "Pending",
        priority: "Low",
        assignedDate: "2024-01-10",
        dueDate: "2024-01-25",
        completionDate: null,
        reopened: false,
        completionTime: null,
      },
      {
        id: 4,
        assignedTo: "Jane Doe",
        status: "Overdue",
        priority: "High",
        assignedDate: "2024-01-15",
        dueDate: "2024-01-30",
        completionDate: null,
        reopened: false,
        completionTime: null,
      },
      {
        id: 5,
        assignedTo: "John Smith",
        status: "Completed",
        priority: "Medium",
        assignedDate: "2024-01-20",
        dueDate: "2024-02-05",
        completionDate: "2024-02-01",
        reopened: false,
        completionTime: 75,
      },
      {
        id: 6,
        assignedTo: "Jane Doe",
        status: "Completed",
        priority: "High",
        assignedDate: "2024-02-01",
        dueDate: "2024-02-15",
        completionDate: "2024-02-14",
        reopened: false,
        completionTime: 85,
      },
      {
        id: 7,
        assignedTo: "John Smith",
        status: "Pending",
        priority: "Medium",
        assignedDate: "2024-02-05",
        dueDate: "2024-02-20",
        completionDate: null,
        reopened: false,
        completionTime: null,
      },
      {
        id: 8,
        assignedTo: "Jane Doe",
        status: "Completed",
        priority: "Low",
        assignedDate: "2024-02-10",
        dueDate: "2024-02-25",
        completionDate: "2024-02-23",
        reopened: false,
        completionTime: 65,
      },
      {
        id: 9,
        assignedTo: "John Smith",
        status: "Overdue",
        priority: "High",
        assignedDate: "2024-02-15",
        dueDate: "2024-03-01",
        completionDate: null,
        reopened: false,
        completionTime: null,
      },
      {
        id: 10,
        assignedTo: "Jane Doe",
        status: "Completed",
        priority: "Medium",
        assignedDate: "2024-02-20",
        dueDate: "2024-03-05",
        completionDate: "2024-03-03",
        reopened: true,
        completionTime: 95,
      },
      {
        id: 11,
        assignedTo: "John Smith",
        status: "Pending",
        priority: "Low",
        assignedDate: "2024-03-01",
        dueDate: "2024-03-15",
        completionDate: null,
        reopened: false,
        completionTime: null,
      },
      {
        id: 12,
        assignedTo: "Jane Doe",
        status: "Completed",
        priority: "High",
        assignedDate: "2024-03-05",
        dueDate: "2024-03-20",
        completionDate: "2024-03-18",
        reopened: false,
        completionTime: 70,
      },
      {
        id: 13,
        assignedTo: "John Smith",
        status: "Completed",
        priority: "Medium",
        assignedDate: "2024-03-10",
        dueDate: "2024-03-25",
        completionDate: "2024-03-24",
        reopened: false,
        completionTime: 80,
      },
      {
        id: 14,
        assignedTo: "Jane Doe",
        status: "Overdue",
        priority: "Low",
        assignedDate: "2024-03-15",
        dueDate: "2024-03-30",
        completionDate: null,
        reopened: false,
        completionTime: null,
      },
      {
        id: 15,
        assignedTo: "John Smith",
        status: "Completed",
        priority: "High",
        assignedDate: "2024-03-20",
        dueDate: "2024-04-05",
        completionDate: "2024-04-02",
        reopened: true,
        completionTime: 105,
      },
      {
        id: 16,
        assignedTo: "Jane Doe",
        status: "Pending",
        priority: "Medium",
        assignedDate: "2024-04-01",
        dueDate: "2024-04-15",
        completionDate: null,
        reopened: false,
        completionTime: null,
      },
      {
        id: 17,
        assignedTo: "John Smith",
        status: "Completed",
        priority: "Low",
        assignedDate: "2024-04-05",
        dueDate: "2024-04-20",
        completionDate: "2024-04-18",
        reopened: false,
        completionTime: 75,
      },
      {
        id: 18,
        assignedTo: "Jane Doe",
        status: "Completed",
        priority: "High",
        assignedDate: "2024-04-10",
        dueDate: "2024-04-25",
        completionDate: "2024-04-23",
        reopened: false,
        completionTime: 65,
      },
      {
        id: 19,
        assignedTo: "John Smith",
        status: "Overdue",
        priority: "Medium",
        assignedDate: "2024-04-15",
        dueDate: "2024-04-30",
        completionDate: null,
        reopened: false,
        completionTime: null,
      },
      {
        id: 20,
        assignedTo: "Jane Doe",
        status: "Completed",
        priority: "Low",
        assignedDate: "2024-04-20",
        dueDate: "2024-05-05",
        completionDate: "2024-05-03",
        reopened: true,
        completionTime: 95,
      },
      {
        id: 21,
        assignedTo: "John Smith",
        status: "Pending",
        priority: "High",
        assignedDate: "2024-05-01",
        dueDate: "2024-05-15",
        completionDate: null,
        reopened: false,
        completionTime: null,
      },
      {
        id: 22,
        assignedTo: "Jane Doe",
        status: "Completed",
        priority: "Medium",
        assignedDate: "2024-05-05",
        dueDate: "2024-05-20",
        completionDate: "2024-05-18",
        reopened: false,
        completionTime: 70,
      },
      {
        id: 23,
        assignedTo: "John Smith",
        status: "Completed",
        priority: "Low",
        assignedDate: "2024-05-10",
        dueDate: "2024-05-25",
        completionDate: "2024-05-24",
        reopened: false,
        completionTime: 80,
      },
      {
        id: 24,
        assignedTo: "Jane Doe",
        status: "Overdue",
        priority: "High",
        assignedDate: "2024-05-15",
        dueDate: "2024-05-30",
        completionDate: null,
        reopened: false,
        completionTime: null,
      },
      {
        id: 25,
        assignedTo: "John Smith",
        status: "Completed",
        priority: "Medium",
        assignedDate: "2024-05-20",
        dueDate: "2024-06-05",
        completionDate: "2024-06-02",
        reopened: true,
        completionTime: 105,
      },
    ],
  }