export const taskData = {
  tasks: [
    {
      id: 1,
      assignedTo: "Hace John",
      status: "Completed",
      priority: "High",
      assignedOn: "2024-01-01",
      deadline: "2024-01-15",
      completed: "2024-01-14",
      reopened: false,
      completionTime: 90,
    },
    {
      id: 2,
      assignedTo: "Liam Mariano",
      status: "Completed",
      priority: "Medium",
      assignedOn: "2024-01-05",
      deadline: "2024-01-20",
      completed: "2024-01-21",
      reopened: true,
      completionTime: 110,
    },
    {
      id: 3,
      assignedTo: "Hace John",
      status: "Pending",
      priority: "Low",
      assignedOn: "2024-01-10",
      deadline: "2024-01-25",
      completed: null,
      reopened: false,
      completionTime: null,
    },
    {
      id: 4,
      assignedTo: "Liam Mariano",
      status: "Overdue",
      priority: "High",
      assignedOn: "2024-01-15",
      deadline: "2024-01-30",
      completed: null,
      reopened: false,
      completionTime: null,
    },
    {
      id: 5,
      assignedTo: "Hace John",
      status: "Completed",
      priority: "Medium",
      assignedOn: "2024-01-20",
      deadline: "2024-02-05",
      completed: "2024-02-01",
      reopened: false,
      completionTime: 75,
    },
    {
      id: 6,
      assignedTo: "Liam Mariano",
      status: "Completed",
      priority: "High",
      assignedOn: "2024-02-01",
      deadline: "2024-02-15",
      completed: "2024-02-14",
      reopened: false,
      completionTime: 85,
    },
    {
      id: 7,
      assignedTo: "Hace John",
      status: "Pending",
      priority: "Medium",
      assignedOn: "2024-02-05",
      deadline: "2024-02-20",
      completed: null,
      reopened: false,
      completionTime: null,
    },
    {
      id: 8,
      assignedTo: "Liam Mariano",
      status: "Completed",
      priority: "Low",
      assignedOn: "2024-02-10",
      deadline: "2024-02-25",
      completed: "2024-02-23",
      reopened: false,
      completionTime: 65,
    },
    {
      id: 9,
      assignedTo: "Hace John",
      status: "Overdue",
      priority: "High",
      assignedOn: "2024-02-15",
      deadline: "2024-03-01",
      completed: null,
      reopened: false,
      completionTime: null,
    },
    {
      id: 10,
      assignedTo: "Liam Mariano",
      status: "Completed",
      priority: "Medium",
      assignedOn: "2024-02-20",
      deadline: "2024-03-05",
      completed: "2024-03-03",
      reopened: true,
      completionTime: 95,
    },
    {
      id: 11,
      assignedTo: "Hace John",
      status: "Pending",
      priority: "Low",
      assignedOn: "2024-03-01",
      deadline: "2024-03-15",
      completed: null,
      reopened: false,
      completionTime: null,
    },
    {
      id: 12,
      assignedTo: "Liam Mariano",
      status: "Completed",
      priority: "High",
      assignedOn: "2024-03-05",
      deadline: "2024-03-20",
      completed: "2024-03-18",
      reopened: false,
      completionTime: 70,
    },
    {
      id: 13,
      assignedTo: "Hace John",
      status: "Completed",
      priority: "Medium",
      assignedOn: "2024-03-10",
      deadline: "2024-03-25",
      completed: "2024-03-24",
      reopened: false,
      completionTime: 80,
    },
    {
      id: 14,
      assignedTo: "Liam Mariano",
      status: "Overdue",
      priority: "Low",
      assignedOn: "2024-03-15",
      deadline: "2024-03-30",
      completed: null,
      reopened: false,
      completionTime: null,
    },
    {
      id: 15,
      assignedTo: "Hace John",
      status: "Completed",
      priority: "High",
      assignedOn: "2024-03-20",
      deadline: "2024-04-05",
      completed: "2024-04-02",
      reopened: true,
      completionTime: 105,
    },
    {
      id: 16,
      assignedTo: "Liam Mariano",
      status: "Pending",
      priority: "Medium",
      assignedOn: "2024-04-01",
      deadline: "2024-04-15",
      completed: null,
      reopened: false,
      completionTime: null,
    },
    {
      id: 17,
      assignedTo: "Hace John",
      status: "Completed",
      priority: "Low",
      assignedOn: "2024-04-05",
      deadline: "2024-04-20",
      completed: "2024-04-18",
      reopened: false,
      completionTime: 75,
    },
    {
      id: 18,
      assignedTo: "Liam Mariano",
      status: "Completed",
      priority: "High",
      assignedOn: "2024-04-10",
      deadline: "2024-04-25",
      completed: "2024-04-23",
      reopened: false,
      completionTime: 65,
    },
    {
      id: 19,
      assignedTo: "Hace John",
      status: "Overdue",
      priority: "Medium",
      assignedOn: "2024-04-15",
      deadline: "2024-04-30",
      completed: null,
      reopened: false,
      completionTime: null,
    },
    {
      id: 20,
      assignedTo: "Liam Mariano",
      status: "Completed",
      priority: "Low",
      assignedOn: "2024-04-20",
      deadline: "2024-05-05",
      completed: "2024-05-03",
      reopened: true,
      completionTime: 95,
    },
    {
      id: 21,
      assignedTo: "Hace John",
      status: "Pending",
      priority: "High",
      assignedOn: "2024-05-01",
      deadline: "2024-05-15",
      completed: null,
      reopened: false,
      completionTime: null,
    },
    {
      id: 22,
      assignedTo: "Liam Mariano",
      status: "Completed",
      priority: "Medium",
      assignedOn: "2024-05-05",
      deadline: "2024-05-20",
      completed: "2024-05-18",
      reopened: false,
      completionTime: 70,
    },
    {
      id: 23,
      assignedTo: "Hace John",
      status: "Completed",
      priority: "Low",
      assignedOn: "2024-05-10",
      deadline: "2024-05-25",
      completed: "2024-05-24",
      reopened: false,
      completionTime: 80,
    },
    {
      id: 24,
      assignedTo: "Liam Mariano",
      status: "Overdue",
      priority: "High",
      assignedOn: "2024-05-15",
      deadline: "2024-05-30",
      completed: null,
      reopened: false,
      completionTime: null,
    },
    {
      id: 25,
      assignedTo: "Hace John",
      status: "Completed",
      priority: "Medium",
      assignedOn: "2024-05-20",
      deadline: "2024-06-05",
      completed: "2024-06-02",
      reopened: true,
      completionTime: 105,
    },
  ],
}